name: Release and Push to maven central
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: Main
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: build artifact
        run: mvn -B clean package
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - id: add-maven-credentials
        name: Add maven credentials
        run: |
          mkdir -p ~/.m2/
          cat <(echo -e "<settings><servers><server><id>ossrh</id><username>${{ vars.OSSRH_USERNAME }}</username><password>${{ secrets.OSSRH_PASSWORD }}</password></server></servers></settings>") > ~/.m2/settings.xml
      - id: publish-to-maven
        name: Publish to Central Repository
        env:
          MAVEN_USERNAME: ${{ vars.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          mvn \
            -P deploy \
            --no-transfer-progress \
            --batch-mode \
            -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} \
            clean deploy